Feature issue#146
alvalfric/indvelopers-frontend pull request #159
Opened 2021-04-24 17:30 UTC by juapormon

Se ha implementado en la vista de detalles del usuario un contador de usuarios seguidos y seguidores con un botón cada uno que te lleva al listado o bien de seguidos o bien de seguidores. En el listado de seguidos se puede dejar de seguir a los usuarios que sigues.

2021-04-24 17:57 UTC, fragarroa requested changes
Se te ha olvidado poner el error boundary. Ponlo de nuevo y apruebo los cambios

2021-04-24 18:04 UTC, Ferwalrod requested changes
El error boundary, que lo has quitado en el index.js
Y en el followListComponent no se si sería mejor encapsular todo en getDetails y en el render poner la condición de que si estas autenticado que use el getDetails(que tendría todo el html y eso) y si no que te redirija a login (esto último es como una sugerencia)

2021-04-25 11:23 UTC, juapormon commented
He añadido ya el errorBoundary y resuelto los nuevos conflictos con develop.

2021-04-25 11:39 UTC, Ferwalrod approved these changes

2021-04-25 15:44 UTC, fragarroa approved these changes

2021-04-25 15:49 UTC, merged